- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE/node.md
- .github/PULL_REQUEST_TEMPLATE/runtime_or_pallets.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- networks/arcadia.json
Add supporting `.md` files:
- issue templates
- pr templates
- contributing instructions
- code of conduct
> github community setup

- .github/PULL_REQUEST_TEMPLATE/generic.md
- .github/PULL_REQUEST_TEMPLATE/node.md
- .github/PULL_REQUEST_TEMPLATE/runtime_or_pallets.md
- correct markdown checklist
- generic template for when we have non code related fixes
> fix github PR templates

- networks/arcadia_alpha_5.json
Add 7 new validators / bootnodes to cope with potential disconnections.
Should help for #40.
> create 7 more validators

- .github/PULL_REQUEST_TEMPLATE/runtime_or_pallets.md
Remind everyone to update their runtime version.
> add sanity section

- README.md
Add Nodle banner to our readme. Also added as a social media preview.
> add nodle banner

- pallets/emergency-shutdown/src/benchmarking.rs
As #71 pointed out we had some warnings, fix them!
> fix warnings in emergency shutdown pallets

- README.md
Add some badges to our readme to represent the status of the project.
> add markdown badges to the readme

- .github/workflows/rust.yml
Restore complete github actions caches and create restoration keys.
> actions caches

- Cargo.lock
- node/Cargo.toml
- node/src/service.rs
- pallets/emergency-shutdown/Cargo.toml
- pallets/poa/Cargo.toml
- pallets/reserve/Cargo.toml
- pallets/root-of-trust/Cargo.toml
- pallets/root-of-trust/rpc/Cargo.toml
- pallets/root-of-trust/rpc/runtime-api/Cargo.toml
- pallets/root-of-trust/src/benchmarking.rs
- pallets/tcr/Cargo.toml
- runtime/Cargo.toml
- runtime/src/implementations.rs
- runtime/src/lib.rs
Bump all deps and code to `alpha.8` which contains bug fixes for the broken release `alpha.7`.
> Fixes #106 and fixes #105.
> upgrade chain to alpha.8

- pallets/tcr/src/benchmarking.rs
- pallets/tcr/src/lib.rs
- pallets/tcr/src/tests.rs
- runtime/src/lib.rs
Make `pallet-tcr` instantiable.
> Fixes #156.
> tcr instances

- node/src/chain_spec.rs
- runtime/src/lib.rs
Create the financila and root commitees. Remap permissions.
> Fixes #157.
> more committees

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/release.yml
- Cargo.lock
- node/Cargo.toml
- node/src/service.rs
- pallets/emergency-shutdown/Cargo.toml
- pallets/emergency-shutdown/src/tests.rs
- pallets/poa/Cargo.toml
- pallets/poa/src/tests.rs
- pallets/reserve/Cargo.toml
- pallets/reserve/src/tests.rs
- pallets/root-of-trust/Cargo.toml
- pallets/root-of-trust/rpc/Cargo.toml
- pallets/root-of-trust/rpc/runtime-api/Cargo.toml
- pallets/root-of-trust/src/tests.rs
- pallets/tcr/Cargo.toml
- pallets/tcr/src/tests.rs
- runtime/Cargo.toml
- runtime/src/implementations.rs
- runtime/src/lib.rs
Prepare node for a rc2 release, we include:
- past changes
- `alpha.8` to `rc2` bump
- rpc fixes
> may-2020.rc2

- types.json
Add JSON types definition for UI and SDK usage.
> Fixes #100.
> add json types spec

- Cargo.lock
- Cargo.toml
- pallets/allocations/Cargo.toml
- pallets/allocations/src/benchmarking.rs
- pallets/allocations/src/lib.rs
- pallets/allocations/src/tests.rs
- pallets/reserve/Cargo.toml
- pallets/reserve/src/lib.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
- support/Cargo.toml
- support/src/lib.rs
Create a module to support nodle allocations.
> Fixes #51.
> allocations module

- Cargo.toml
- node/src/chain_spec.rs
- pallets/reserve/src/benchmarking.rs
- pallets/reserve/src/lib.rs
- pallets/reserve/src/tests.rs
- runtime/src/lib.rs
Create additional financial reserves as requested by the legal / finance team.
> more reserves

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- node/src/chain_spec.rs
- pallets/allocations/src/benchmarking.rs
- pallets/allocations/src/lib.rs
- pallets/allocations/src/tests.rs
- pallets/grants/Cargo.toml
- pallets/grants/README.md
- pallets/grants/src/benchmarking.rs
- pallets/grants/src/lib.rs
- pallets/grants/src/mock.rs
- pallets/grants/src/tests.rs
- pallets/reserve/src/tests.rs
- pallets/root-of-trust/src/tests.rs
- pallets/tcr/src/benchmarking.rs
- pallets/tcr/src/tests.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
Introduce a module to issue vested grants with an optional cliff. One can make multiple grants to one entity and the financial committee cancel them.
> Fixes #179.
> grants module

- .github/PULL_REQUEST_TEMPLATE.md
- pallets/grants/src/lib.rs
- runtime/src/lib.rs
- types.json
Just a few forgotten things to be included.
> grants fixes

- Cargo.lock
- node/src/chain_spec.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
Types additions, deps bumps etc...
> repo cleaning

- pallets/amendments/src/lib.rs
- runtime/src/lib.rs
Describe what is changed and your reasoning.
> fix amendments pallet for system upgrades

- Cargo.lock
- Cargo.toml
- executor/Cargo.toml
- executor/src/lib.rs
- node/Cargo.toml
- node/src/chain_spec.rs
- node/src/command.rs
- node/src/service.rs
- primitives/Cargo.toml
- primitives/src/lib.rs
- runtime/Cargo.toml
- runtime/src/constants.rs
- runtime/src/implementations.rs
- runtime/src/lib.rs
Was attempting to debug a sync issue and ended up refactoring the node code to make it more parity like.
> simple fixes and refactoring

- pallets/allocations/src/lib.rs
- pallets/amendments/src/lib.rs
- pallets/grants/src/benchmarking.rs
- pallets/grants/src/lib.rs
- pallets/reserve/src/lib.rs
- pallets/root-of-trust/rpc/src/lib.rs
- pallets/root-of-trust/rpc/src/rpc_errors.rs
- pallets/root-of-trust/src/lib.rs
- pallets/tcr/src/lib.rs
- runtime/src/lib.rs
Describe what is changed and your reasoning.
> qsp audit fixes

- Cargo.lock
- node/Cargo.toml
- node/src/chain_spec.rs
- node/src/rpc.rs
- runtime/Cargo.toml
- runtime/src/lib.rs
Integration of pallet-contracts
Fixes : https://github.com/NodleCode/chain/issues/78
> pallet-contracts bringup

- Cargo.lock
- executor/Cargo.toml
- node/Cargo.toml
- pallets/allocations/Cargo.toml
- pallets/amendments/Cargo.toml
- pallets/emergency-shutdown/Cargo.toml
- pallets/grants/Cargo.toml
- pallets/poa/Cargo.toml
- pallets/reserve/Cargo.toml
- pallets/root-of-trust/Cargo.toml
- pallets/root-of-trust/rpc/Cargo.toml
- pallets/root-of-trust/rpc/runtime-api/Cargo.toml
- pallets/tcr/Cargo.toml
- primitives/Cargo.toml
- runtime/Cargo.toml
- support/Cargo.toml
Releases 2.0.2. Mostly bugfixes since the last version and getting ready for deployment on the mainnet.
> release 2.0.2

- runtime/src/pallets_consensus.rs
Describe what is changed and your reasoning.
> OnOffenceHandler set to Staking

- .maintain/release.sh
Describe what is changed and your reasoning.
> create script for easier release process

- node/src/chain_spec.rs
- pallets/nodle-staking/src/migrations.rs
- runtime/src/lib.rs
- runtime/src/migrations.rs
- runtime/src/pallets_util.rs
phase-0 chaos test runtime migration updates
> phase-0 chaos test runtime migration updates

- pallets/nodle-staking/src/hooks.rs
- pallets/nodle-staking/src/lib.rs
- pallets/nodle-staking/src/migrations.rs
- pallets/nodle-staking/src/mock.rs
- pallets/nodle-staking/src/tests.rs
- runtime/src/pallets_consensus.rs
Integration of ValidatorRegistration check on nodle-staking Done
> integration of ValidatorRegistration check on nodle-staking

- .github/workflows/docker.yml
- .maintain/docker/Dockerfile
Just tested in an ARM VM, seems like we have an exec format error. This PR fixes it by supporting one more arch and updating the dockerfile a bit
> fix docker arm support

- node/src/command.rs
- use commit hash as impl version
- default to mainnet
> cli metadata update

- runtime/src/lib.rs
> add static enum ids to construct_runtime enum

- node/src/chain_spec/cs_eden.rs
Enable endowed accounts for local genesis
> Enable endowed accounts

- .github/workflows/ci.yml
- Cargo.lock
- node/Cargo.toml
- node/src/cli.rs
- node/src/command.rs
- runtimes/eden/Cargo.toml
- runtimes/eden/src/lib.rs
- runtimes/main/Cargo.toml
- runtimes/main/src/lib.rs
- runtimes/staking/Cargo.toml
- runtimes/staking/src/lib.rs
Ready for your review after passing the following tests:
> feat: support try-runtime for all our runtimes

- Cargo.lock
- pallets/grants/src/lib.rs
- pallets/grants/src/tests.rs
- pallets/tcr/src/lib.rs
- runtimes/eden/src/version.rs
- runtimes/main/src/version.rs
- runtimes/staking/src/version.rs
- prevent vesting to self
- remove redundant check
- fix regression test
- remove redundant variable
- cargo audit fix
- bump versions
> minor refactorings

- node/res/staking.full.json
- node/res/staking.json
Modify the staking chain spec a little bit:
- add telemetry
- update names to make them differentiable
- change token symbol to avoid confusions
- add default bootnodes
> Update staking spec

- pallets/staking/src/lib.rs
- pallets/staking/src/tests.rs
Halborn audit review fixes ...
Related to ...
* [(2) Incorrect Logic](https://www.notion.so/nodle/Incorrect-Logic-29f999868e9f4ee7ab1b82652131c60a)
* [(2) Missing Sanity Checks](https://www.notion.so/nodle/Missing-Sanity-Checks-385d538322674497863d9bc0b548afe7)
* [Halborn fixes · Issue #117 · NodleCode/chain-workspace](https://github.com/NodleCode/chain-workspace/issues/117)
> Halborn audit review fixs

- pallets/wnodl/src/lib.rs
> doc(wnodl-pallet): fix function doc comments

- node/res/eden.json
- scripts/vnv-boot-collators/generate-authority-keys.sh
- scripts/vnv-boot-collators/init-env.sh
- scripts/vnv-boot-collators/inject-session-keys.sh
> chainspec boot nodes update

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- build atop default ubuntu image
- add github cli and docker support
> improve devcontainer

- .github/workflows/ci.yml
> Use the archive node of Onfinality for try-runtime tests

- .devcontainer/devcontainer.json
- use saner defaults
- preinstall extensions
> devcontainer extensions

- .github/workflows/doc.yml
Patch for the issue, [Fix Rust Autodoc action step for builds #201](https://github.com/NodleCode/chain-workspace/issues/201)
> patch - Fix Rust Autodoc action step for builds #201

- Cargo.lock
- nodes/parachain/src/chain_spec.rs
- runtimes/eden/Cargo.toml
- runtimes/eden/src/lib.rs
- runtimes/eden/src/pallets_governance.rs
- runtimes/eden/src/version.rs
- remove sudo from runtime
- remove sudo from spec
> remove sudo pallet

- .maintain/release.sh
- Cargo.lock
- node/Cargo.toml
- pallets/allocations/Cargo.toml
- pallets/amendments/Cargo.toml
- pallets/emergency-shutdown/Cargo.toml
- pallets/grants/Cargo.toml
- pallets/mandate/Cargo.toml
- pallets/poa/Cargo.toml
- pallets/reserve/Cargo.toml
- pallets/staking/Cargo.toml
- primitives/Cargo.toml
- runtimes/eden/Cargo.toml
- support/Cargo.toml
- modify script to be PR friendly
- bump version for release
> prepare 2.0.20

- pallets/allocations/Cargo.toml
- pallets/allocations/src/benchmarking.rs
I just committed the changes I suggested in the original PR here for convenience.
> Remove unwrap in constructing a BoundedVec

- Cargo.lock
- node/Cargo.toml
- pallets/allocations/Cargo.toml
- pallets/grants/Cargo.toml
- pallets/mandate/Cargo.toml
- pallets/poa/Cargo.toml
- pallets/reserve/Cargo.toml
- pallets/staking/Cargo.toml
- primitives/Cargo.toml
- runtimes/eden/Cargo.toml
- support/Cargo.toml
> chore: prepare for releasing 2.0.21

- .maintain/srtool.sh
Use the latest release of paritytech/srtool
> chore: update srtool.sh

- .github/workflows/srtool.yml
Fix CI Build | srtool version upgrade
> srtool version upgrade

- node/res/eden-testing.json
- node/res/eden-testing.spec.json
- node/res/eden.json
- node/res/eden.spec.json
Close NodleCode/chain-workspace#163
> rpc system.properties will return ss58Format

- .devcontainer/Dockerfile
> Change node version to 18

- Cargo.lock
Cargo.lock file was not updated
> [Fix] srtool was failing after the merge of PR #687

- .github/workflows/ci.yml
actions-rs gh actions is unmaintained this is a fork which is slightly more maintained
> Replace actions-rs/clippy with maintained fork

- .github/workflows/ci.yml
- Cargo.lock
- node/src/command.rs
- node/src/service.rs
- pallets/allocations/src/lib.rs
- pallets/allocations/src/tests.rs
- pallets/grants/src/lib.rs
- pallets/grants/src/tests.rs
- pallets/staking/src/lib.rs
- pallets/staking/src/tests.rs
- pallets/staking/src/types.rs
- replace tarpaulin with cargo llvm-lcov
- update toolchain to latest nightly
- AI clean up `cargo clippy --fix`
> Replace tarpaulin in CI and update toolchain to latest nightly

- .devcontainer/devcontainer.json
- isolate settings to codespaces only
- remove non project specific extensions
- prebuild test compilation
- configure sane host defaults
> optimize devcontainer

- runtimes/eden/src/pallets_consensus.rs
- runtimes/eden/src/pallets_governance.rs
- lower min candidates to 3
- allow supermajority of tech comm to take special collator selection actions
> collator selection config optim

- .github/workflows/srtool.yml
This is now able to create a release automatically from a tag
Example release is generated here: https://github.com/NodleCode/chain/releases/tag/untagged-4b4bd7c5ae73fbfd223a
> Chore/20230518 release-build

- .github/workflows/docker.yml
- .github/workflows/srtool.yml
Build release jobs on tags
Close #747
> Build release jobs on tags

- runtimes/eden/src/version.rs
> Increment spec version for next release Prepare for release 2.2.2

- .github/workflows/ci.yml
- .github/workflows/doc.yml
**This is a WIP and should be merged only if CI is happy**
> setup sccache for faster CI

- node/Cargo.toml
- pallets/allocations/Cargo.toml
- pallets/grants/Cargo.toml
- pallets/mandate/Cargo.toml
- pallets/reserve/Cargo.toml
- pallets/sponsorship/Cargo.toml
- pallets/uniques/Cargo.toml
- primitives/Cargo.toml
- runtimes/eden/Cargo.toml
- runtimes/eden/src/version.rs
- support/Cargo.toml
> chore: prepare for releasing 2.4.1

- Cargo.lock
- Cargo.toml
- node/Cargo.toml
- node/src/chain_spec.rs
- node/src/command.rs
- runtimes/eden/Cargo.toml
- runtimes/eden/src/lib.rs
- runtimes/eden/src/xcm_config.rs
Replace deprecated types FungibleAdapter and GenesisSpec::builder
Consolidate local dev testnets to once config
> Replace deprecated types and consolidate development testnets

- .github/Dockerfile
- Dockerfile
The docker should contain the latest runtime was which is capable of supporting Ledger
> feat: on-chain-release-build for docker image

- runtimes/eden/build.rs
- runtimes/eden/src/version.rs
Add missing bit for supporting Ledger Polkadot App
> fix: metadata hash singed extra

- .github/workflows/srtool.yml
- node/src/chain_spec.rs
- runtimes/eden/build.rs
- runtimes/eden/src/lib.rs
- runtimes/eden/src/version.rs
The aim was to get it work with Talisman wallet. The approach is to produce several wasm binaries for chain with different token names.
> Fix metadata hash for testnet and local chain 
