NodleCode/chain

networks/arcadia.json

#23 included by mistake a commit that changed the network id in our chainspec,
go back.

revert back to old network id

---

networks/arcadia.json
runtime/src/lib.rs

Thanks to the precious help received at paritytech/subport#2 we
discovered that we need to bump `spec_version` in order to avoid
the panic reported in #21.
Fixes #21.

spec version bump

---

pallets/allocations/src/lib.rs
pallets/allocations/src/tests.rs
pallets/poa/src/lib.rs
pallets/poa/src/tests.rs
pallets/reserve/src/lib.rs
pallets/reserve/src/tests.rs
runtime/src/constants.rs
runtime/src/implementations.rs
runtime/src/lib.rs
src/chain_spec.rs
src/cli.rs
src/command.rs
src/main.rs
src/service.rs

According to the GPLv3 license we should add the header
to our source code files.

add gplv3 header to the source code files

---

Cargo.lock
Cargo.toml

Allows running the node with `--wasm-execution compiled` which gives a nice speedup on initial sync with wasm runtime (about 4-5x on my computer).

cli: enable wasmtime

---

.maintain/docker/Dockerfile

Quite some changes were introduced in #33, however this broke the docker container
when trying to add the chain spec files to it. This PR fixes it.

add trailing slash

---

networks/arcadia_alpha_5.json

Had forgotten to fill the validators members.

chain spec fix

---

Cargo.toml

`frame-benchmarking-cli` was marked as `optional` which prevented the
compiling of the node without the benchmark options.

make frame-benchmarking-cli non optional

---

pallets/reserve/src/lib.rs
pallets/reserve/src/tests.rs
runtime/src/lib.rs

`apply_as` will be useful when trying to send transaction coming **from** the company reserve (for instance, creating vested grants).
Fixes #31.
> No need to push an upgrade for this, we will bundle changes into a network wide upgrade later.

reserve apply_as

---

pallets/reserve/src/lib.rs
pallets/reserve/src/tests.rs
runtime/src/lib.rs

In order to support a more robust governance model, copy parity's pattern and let root override `EnsureOrigin` calls.
Fixes #56.

try origin or root

---

.github/PULL_REQUEST_TEMPLATE/runtime_or_pallets.md
Cargo.lock
Cargo.toml
pallets/emergency-shutdown/Cargo.toml
pallets/emergency-shutdown/src/benchmarking.rs
pallets/emergency-shutdown/src/lib.rs
pallets/emergency-shutdown/src/tests.rs
runtime/Cargo.toml
runtime/src/lib.rs

This pallet exposes a function to `toggle` the `shutdown` state, other pallets can check this value and decide on wether they should approve a transaction or not.
Fixes #55.

emergency shutdown

---

pallets/allocations/src/lib.rs
pallets/allocations/src/tests.rs
runtime/src/lib.rs

Some tuning for our june upgrade. Also apply learning from our launch.

june tuning

---

Cargo.lock
node/Cargo.toml
node/src/command.rs
node/src/service.rs
pallets/allocations/Cargo.toml
pallets/amendments/Cargo.toml
pallets/emergency-shutdown/Cargo.toml
pallets/grants/Cargo.toml
pallets/poa/Cargo.toml
pallets/reserve/Cargo.toml
pallets/root-of-trust/Cargo.toml
pallets/root-of-trust/rpc/Cargo.toml
pallets/root-of-trust/rpc/runtime-api/Cargo.toml
pallets/tcr/Cargo.toml
runtime/Cargo.toml
runtime/src/lib.rs
support/Cargo.toml

Support substrate's RC6 release.

bump deps and code to substrate rc6

---

.maintain/chaos/docker-compose.yml

Create a "chaos" config that can be used to play a local network in docker containers and play around with it.
> Fixes #252.

docker-compose for local network

---

.maintain/chaos/docker-compose.yml
runtime/src/implementations.rs
runtime/src/lib.rs

Upgrading straight to rc6 from rc2 caused some issues due to some migrations having been removed. This PR fixes this by adding the required migrations inside the runtime code.

fix upgrade to rc6

---

pallets/amendments/src/lib.rs
runtime/src/lib.rs

Seems like the docstring was erroneous, fix it.

fix doc string in amendments pallet

---

node/src/chain_spec.rs
node/src/command.rs
runtime/src/lib.rs

- create dummy chain spec to avoid duplicating test balances when forking
- write runtime migration to fix the vesting schedules
- new main chain spec
This PR modifies the mainnet chain spec to be able to restart the chain with the old network's state.
We had to do a few wizardy:
- implement some runtime migrations to recompute vested grants
- create a "dummy" network to avoid merging a test config with a production one (aka having the test accounts Alice, Bob and others with money)
- make sure the new runtime is part of the chain spec
Tested this locally with success. Next step is to deploy and see what happens.

fix stall spec

---

pallets/reserve/src/lib.rs
runtime/src/lib.rs

Should have been caught during the previous audits. But basically we were dispatching as `root` instead of the module's account id which prevented us to call some `ensure_signed` functions.

fix apply as dispatch origin and make it signed from the module id

---

.gitignore
pallets/grants/src/benchmarking.rs
pallets/grants/src/lib.rs
pallets/grants/src/tests.rs
runtime/src/lib.rs

Due to the previous bug which we fixed we may have some grants with a "corrupted" state which would make it impossible to correctly cancel and redo those grants. This PR fixes this

grants cancelling: limit to free balance to support corrupted states

---

.github/workflows/ci.yml

Stop running tests on macos as it slows things down for not much benefits. The code runs the same on ubuntu and macos anyways.

no longer run tests on macos

---

pallets/reserve/src/lib.rs
runtime/src/version.rs

Seems like we had a regression here. Get rid of the runtime migrations and prepare for a hotfix upgrade.

hotfix reserve apply as

---

node/src/chain_spec.rs

When testing our allocations script we always have to add more authorities to our committees to match what we have in prod. This changes the chain spec to match this and avoid having to do it manually again.

make the dev setup more similar to a prod setup

---

pallets/allocations/src/lib.rs
pallets/grants/src/lib.rs

In block explorer we indexing events. To do it we store it as json field in Postgresql. But polkadot.js library (and substrate API interfaces) doesn't provide information about field names. But they put it in documentation like it
```
/// Transfer succeeded. \[from, to, value\]
Transfer(T::AccountId, T::AccountId, T::Balance),
``` 
This PR contains updates in `NewAllocation` documentation

Added event parameter annotation for NewAllocation event

---

pallets/nodle-staking/src/lib.rs
pallets/nodle-staking/src/tests.rs

`T::Currency::set_lock()` & `T::Currency::remove_lock()` are used to update the account consumers.
`system::Pallet::<T>::inc_consumers()` & `system::Pallet::<T>::dec_consumers()` are removed to avoid 
duplicate functionality.

Bug_fix: nominator_nominate() is updated with inc_consumers()

---

Cargo.lock
pallets/grants/src/lib.rs
pallets/grants/src/mock.rs
runtimes/eden/Cargo.toml
runtimes/eden/src/implementations.rs
runtimes/eden/src/pallets_util.rs
runtimes/main/src/pallets_util.rs

Integration of Block Number provider interface to Vesting pallet.

pallet grants BlockNumberProvider integration

---

pallets/allocations/src/benchmarking.rs
pallets/allocations/src/lib.rs
pallets/amendments/src/benchmarking.rs
pallets/emergency-shutdown/src/benchmarking.rs
pallets/grants/src/benchmarking.rs
pallets/reserve/src/benchmarking.rs
pallets/root-of-trust/src/benchmarking.rs
pallets/staking/src/benchmarking.rs
pallets/tcr/src/benchmarking.rs

Currently, several of our benchmarks output warnings concerning unused imports in addition to the benchmark data we requested. This is unaffected by the `--quiet` flag, and in at least one case, we may be compiling more dependency code than necessary.
This PR resolves the above issues through use of Rust compiler flags.

refactor: improve benchmark compile output

---

pallets/allocations/src/lib.rs
pallets/allocations/src/tests.rs

A trivial change that adds an early return to the allocate extrinsic.

feat(pallet-allocations): fast return on zero allocation

---

.github/workflows/ci.yml

Installing ubuntu native dependencies had become dead as of a previous process simplification. It turns out CI runs fine without it.

fix(ci): remove dead code

---

runtimes/main/src/lib.rs
runtimes/main/src/version.rs

This is going to address the test net upgrade issue. We need to make sure that after we upgraded the test net and then our main-net, we actually remove this code as it's not checking for any versions now. 
Also as part of runtime migration we have addressed a discrepancy that was once lurked in the storage and had made come committees to have different members than their corresponding membership pallets. 
NOTE: This wouldn't pass the try-runtime test. We would need to merge it as it is. The reason being there are some known defects in the current storage which will be addressed by this PR itself (by overwriting to those storage prefixes)

fix: runtime upgrade for pallet memberships

---

node/src/chain_spec/cs_main.rs
pallets/wnodl/src/benchmarking.rs
pallets/wnodl/src/lib.rs
pallets/wnodl/src/tests.rs

As suggested [here](https://www.notion.so/nodle/Missing-Zero-Value-Check-ce0db63556c74ff29690526f019fa979), be defensive against zero amount even when it's safe but the operation is considered useless or wasteful.
This PR contains an incidental change for min and max wrap for the development chain spec that would make the tests easier.

feat(wnodl-pallet): be defensive against zero amount

---

pallets/wnodl/src/lib.rs
pallets/wnodl/src/mock.rs
runtimes/main/src/pallets_wnodl.rs

Origin for initiating and settling wrapping from reserve fund will be configurable for re-users of the pallet but will keep as root for nodle-main.

feat(wnodl-pallet): make origin for privillaged functions configurable

---

pallets/allocations/src/lib.rs
pallets/allocations/src/tests.rs
runtimes/eden/src/pallets_nodle.rs
runtimes/eden/src/version.rs
runtimes/main/src/pallets_nodle.rs
runtimes/main/src/version.rs

Modify the way allocations are allocated to mint the coins to a special account before transfering them to the proper account. This will allow each and every allocation to show up in a `balances.Transfer` event from this same well known address (`4jbtsgNhpGAzdEGrKRb7g8Mq4ToNUpBVxeye942tWfG3gcYi`), thus making it possible for apps like Nodle Cash to fetch such events and correctly identify them as allocations on an API like Subscan.
Also modifies the way we verify the existential deposit requirements of each allocation to save on DB reads.

send allocations as a balance transfer

---

runtimes/eden/src/constants.rs
runtimes/eden/src/pallets_system.rs
runtimes/eden/src/version.rs

Our previous constants naming for currency units was based on another codebase, most likely Substrate's template or Polkadot. It was confusing to say the least. This PR changes this creating new, more expressive, constants and replacing the old ones. A test was added to make sure my math is correct.

refactor constants

---

runtimes/eden/src/constants.rs
runtimes/eden/src/version.rs

The current version of the parachain assumes a maximum block weight of 2 seconds, however, the default for parachains is actually of .5 seconds (as used by Acala, Statemine, and others). This could explain the unstable block time on eden or paradis.

fix: reduce maximum weight of eden to .5 seconds

---

nodes/parachain/res/eden-testing.json

Update the IDs in the chain spec to clearly differentiate from the previous chain spec and avoid contamination of the collators.

update eden chain and protocol ids

---

pallets/mandate/src/lib.rs
pallets/reserve/src/lib.rs
runtimes/eden/src/version.rs
runtimes/main/src/version.rs

SRLabs performed a technical review of our pallets and runtime. The weight functions in the `apply_as` and `apply` extrinsics is suffering from potential integer overflows and exponential complexity issues which could lead to badly computed weights/fees. This PR addresses this.

technical review: fix weight computation

---

.github/workflows/binary.yml
.github/workflows/ci.yml

cleanup actions

---

Dockerfile

We no longer need a custom rococo chain spec. Looks like it was updated within the latest polkadot release.

no need for roc chain spec

---

pallets/grants/src/benchmarking.rs
pallets/grants/src/lib.rs
pallets/grants/src/tests.rs

prevent a transaction failure when cancel_all_vesting_schedules was not limited to the free balance

fix(pallet-grants): prevent a transaction failure

---

pallets/mandate/src/lib.rs

Part of [#173](https://github.com/NodleCode/chain-workspace/issues/173)
**HighLights**
- Not much changes, removed `without_storage_info` from pallet

Remove without_storage_info for the mandate pallet

---

runtimes/eden/src/version.rs

Our previous solo main net's tx version was 3.55.0. This issue is raised by Zondax as Ledger Live would not allow an application's upgrade for Nodle on Ledger otherwise.

fix(runtime-eden): parachain's tx version should be higher than previous solo chain

---

node/src/chain_spec.rs
node/src/service.rs
pallets/mandate/src/lib.rs
pallets/reserve/src/lib.rs
pallets/staking/src/lib.rs
runtimes/eden/src/pallets_system.rs
runtimes/eden/src/pallets_util.rs

Should make the build clean.
Removed `1 * something`  it existed only for consistency with other values in the lists
`derive_partial_eq_without_eq` implemented suggestion but another source was included in the same file so I also silenced it
`#[allow(clippy::type_complexity)]` yes the types are complex let's just acknowledge that
`#[allow(clippy::boxed_local)]` not sure if we should change the code or silence the warning so I silenced it.

Silence a few clippy warnings

---

.github/workflows/ci.yml

`try-runtime` target needs +nightly toolchain to be default ...

Fix to CI/CD build try-runtime error

---

.github/workflows/ci.yml
Cargo.lock
node/Cargo.toml
node/src/chain_spec.rs
pallets/allocations/Cargo.toml
pallets/allocations/src/benchmarking.rs
pallets/allocations/src/lib.rs
pallets/allocations/src/migrations.rs
pallets/allocations/src/tests.rs
pallets/grants/Cargo.toml
pallets/mandate/Cargo.toml
pallets/poa/Cargo.toml
pallets/reserve/Cargo.toml
pallets/staking/Cargo.toml
primitives/Cargo.toml
runtimes/eden/Cargo.toml
runtimes/eden/src/pallets_nodle.rs
support/Cargo.toml

Part of [#173](https://github.com/NodleCode/chain-workspace/issues/173)
**HighLights**
- Storage `Oracles` is moved to bounded vector.
- Upperlimit  for  `Oracles`  is Configured via `MaxOracles`.
- Introduced new events `OracleMembersUpdated(u32)` & `OracleMembersOverFlow(u32, u32)`
- UnitTest Extension :: Done
- Runtime Integration :: Done
- Storage Migration (try_runtime) :: Done
- Benchmarking
**TODO**
**Ready for Intake Review**

Remove without_storage_info for the allocations pallet V2

---

.github/workflows/ci.yml
pallets/allocations/src/lib.rs
pallets/allocations/src/migrations.rs

Remove the attempt to remove CoinsConsumed which was already removed in a previous deployment of release 2.0.21. Fix the try-runtime test which could have indicated this error to us before merging the migration code.

fix(pallet-allocations): fix try-runtime and the migration code

---

runtimes/eden/src/pallets_util.rs

**Would this be merged, we need a deployment before the end of the month for our event.**
Modify base fees for the `uniques` pallet:
- make it slightly more expensive to create a new class
- make it slightly more expensive to create a new instance
- make it much cheaper to register metadatas (base and per byte fee)
The goal here is to make the fees make a bit more sense when creating big collections while ensuring we still maintain economic consistency.
- creating a class with metadata: $ c_{class} = 10 + 10 + 46*1 = 66 $
- creating one instance with metadata: $ c_{instance} = 0.1 + 10 + 46*1 = 56.1 $
Creating a collection of 50k NFTs with a metadata size of 46 bytes (IPFS CID) will cost: $ c_{class} + 50,000*c_{instance} = 66 + 50,000*56.1 = 2,805,066 $
This seems like a lot for just 50k …

review uniques economics

---

runtimes/eden/src/lib.rs

Backport paritytech/substrate#11699 so we can start monitoring our storage size.
Learning from the Parity Parachain Summit, it sounds like we need to start
limited our storage element sizes in order to keep our PoV size under control
and avoid having our parachain stop.

backport parity storage limitation test

---

node/src/chain_spec.rs
runtimes/eden/src/lib.rs
runtimes/eden/src/pallets_governance.rs
runtimes/eden/src/version.rs

Explicitly create a dao reserve for future plumbing in the code. Marked as
`EnsureNever` so that nobody can use it (yet).

dao reserve

---

Cargo.lock
node/Cargo.toml
node/src/service.rs
pallets/allocations/Cargo.toml
pallets/grants/Cargo.toml
pallets/mandate/Cargo.toml
pallets/poa/Cargo.toml
pallets/reserve/Cargo.toml
pallets/staking/Cargo.toml
primitives/Cargo.toml
runtimes/eden/Cargo.toml
runtimes/eden/src/version.rs

Upgrade to polkadot v0.9.28

---

.github/workflows/srtool.yml

I tested the change here: https://github.com/NodleCode/chain/actions/runs/3086849701. Without it we would get:
>  error[E0658]: use of unstable library feature 'vec_retain_mut'
>  --> /cargo-home/git/checkouts/substrate-7e08433d4c370a21/34a0621/client/transaction-pool/src/graph/validated_pool.rs:207:12
>  |
>  207 | sinks.retain_mut(|sink| match sink.try_send(*hash) {
>  | ^^^^^^^^^^
>  |
>  = note: see issue #90829 <https://github.com/rust-lang/rust/issues/90829> for more information
>  = help: add `#![feature(vec_retain_mut)]` to the crate attributes to enable

build: fix srtool build

---

pallets/allocations/src/benchmarking.rs
pallets/allocations/src/lib.rs
pallets/allocations/src/tests.rs
pallets/allocations/src/weights.rs

Move quota calculations to happen in the first successful `batch` call in a fiscal period. Same for quota renewal that would happen in the first successful call in a session period. 
This new approach relies on adding two new storage for storing the schedules for quota calculations and renewals. The additional cost to most of the batch calls would be only three additional storage reads. However in those batch calls where the calculation and or renewal of quota is needed the cost would be more. 
The benefit of this new approach is that it doesn't rely on any block initialisation or finalisation process. And if there is no batch call in a block, there is now overhead related to the allocations for the block. The implementation is also capable of being based on both relay chain block numbers …

fix: allocations access to the relay chain block number

---

Cargo.lock
node/Cargo.toml
pallets/allocations/Cargo.toml
pallets/grants/Cargo.toml
pallets/mandate/Cargo.toml
pallets/poa/Cargo.toml
pallets/reserve/Cargo.toml
pallets/staking/Cargo.toml
primitives/Cargo.toml
runtimes/eden/Cargo.toml
runtimes/eden/src/version.rs
support/Cargo.toml

A change in the uniques pallet coming through using polkadot 0.9.28, would require us to bump the tx version and rebuild the nodle app on Ledger.

chore: prepare for releasing 2.0.24

---

node/src/chain_spec.rs
runtimes/eden/Cargo.toml
runtimes/eden/src/lib.rs
runtimes/eden/src/pallets_parachain.rs
runtimes/eden/src/xcm_config.rs

Integration and configuration of the pallet xcm to allow cross-chain messaging.

XCM Integration 

---

.github/workflows/ci.yml
Cargo.lock
runtimes/eden/src/pallets_util.rs

If the space allowed for a few more bytes IPFS:// urls could for instance be used.

Increase max nft string length

---

.github/workflows/ci.yml
Cargo.lock
node/Cargo.toml
pallets/allocations/Cargo.toml
pallets/grants/Cargo.toml
pallets/mandate/Cargo.toml
pallets/reserve/Cargo.toml
primitives/Cargo.toml
runtimes/eden/Cargo.toml
runtimes/eden/src/migrations.rs
runtimes/eden/src/version.rs
support/Cargo.toml

The on chain version of the pallets should match the pallets versions for newly added pallets. Also the safe xcm version for PolkadotXcm should be set manually.

correct storage of new pallets and prepare release

---

runtimes/eden/src/weights/mod.rs
runtimes/eden/src/xcm_config.rs

We refer to NODL as an asset represented by our pallet instance 2 (pallet-balances) on our parachain and this location should be regarded as a known asset type.
Also fix xTokens to use the same weigher as xcm -executor.

fix(runtime-eden): recognise xtokens' nodlNative as known asset

---

Cargo.lock
node/Cargo.toml
pallets/allocations/Cargo.toml
pallets/grants/Cargo.toml
pallets/mandate/Cargo.toml
pallets/reserve/Cargo.toml
primitives/Cargo.toml
runtimes/eden/Cargo.toml
runtimes/eden/src/version.rs
support/Cargo.toml

We need to have a minor release which contains the fix for our xtoken weigher.

chore: prepare to release 2.0.30

---

.github/workflows/ci.yml
.github/workflows/doc.yml
.github/workflows/docker.yml
.github/workflows/srtool.yml

Reduce the runner size for non priority workflows and optimize frequency of runs (for instance we really only need a docker container to be built once a release is issued).
Beyond being less noisy and failing faster when necessary, this might save us a little money.

Optimize github actions to be cheaper and cleaner

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/devcontainer.yml

- only run build, not tests
- create our own cached image in CI
- doc devcontainer
- use prebuilt devcontainer
- exclude nodle-parachain
- schedule devcontainer build for once a week

fix and improve devcontainer prebuild

---

runtimes/eden/src/version.rs

This macro puts the `RuntimeVersion` into a custom section in the wasm file. This speedups reading the `RuntimeVersion`.

Use `runtime_version` attribute macro

---

node/res/eden-testing.json

A previous collator is now terminated and a full node is added to serve the light client connections. Also there is a "ws" part added to the structure of the previous addresses recently.

Update p2p addresses in eden-testing.json

---

node/Cargo.toml
pallets/allocations/Cargo.toml
pallets/grants/Cargo.toml
pallets/mandate/Cargo.toml
pallets/reserve/Cargo.toml
primitives/Cargo.toml
runtimes/eden/Cargo.toml
support/Cargo.toml

Bump release version to 2.2.2

---

.devcontainer/Dockerfile
.github/Dockerfile
.github/workflows/ci.yml
.github/workflows/devcontainer.yml
Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/command.rs

deprecate try-runtime feature in favor of new CLI from Parity

---

pallets/reserve/src/lib.rs
pallets/reserve/src/tests.rs

This leads to batch_all also forwarding errors if `reserve.apply_as` fails.
See [this proposal](https://nodle.subscan.io/tech/313?tab=votes) for an example of a proposal which partially fails but still gets partially applied which is not a desired border effect.

forward errors when dispatch fail on reserve.apply_as

---

runtimes/eden/src/version.rs

Tx version must always go up (or remain the same if no metadata changes) irrespective of the spec version.

fix(runtime-eden): correct tx version

---

.github/workflows/ci.yml

We will need to re-run try-runtime tests later for a specific tag (release) close to the deployment time.

chore: allow us to run some CI jobs manually when we need

---

.github/workflows/ci.yml
.github/workflows/doc.yml

- Try runtime will take about one minute to check every time now. Before there could be a penalty of 10-15 minutes if the snap was not in the cache and if the test failed the cache would not have been updated so the next check would also be slow.
- Executor size for try-runtime is reduced from 8 core to standard. 
- doc generation is tested on every PR, and ignores warning. (Autodoc is not the place to notify us about warnings)

Improve stability for try-runtime flow

---

Cargo.lock
Cargo.toml
node/Cargo.toml
pallets/grants/Cargo.toml
pallets/grants/src/benchmarking.rs
pallets/grants/src/lib.rs
pallets/grants/src/tests.rs
pallets/grants/src/weights.rs
runtimes/eden/src/weights/pallet_grants.rs

1. The bridge is initiated by the user/grant owner similar to how bridging of free tokens currently happening.
2. The bridge_all_vesting_schedules function is added to to pallet-grants which will be very similar to cancel_all_vesting_schedules with the difference that for this one only the owner of the grant and not the governance of the chain can initiate a bridge for locked tokens.
3. Similar to cancel_… bridge_all_vesting_schedules  will first do a claim for the user so they get all their free-able tokens into their own account first.
4. bridge_all_vesting_schedules burns the locked grants of the user and remove their details as well if it succeeds.
5. bridge_all_vesting_schedules will then generate an event traceable by our bridge off-chain oracles which indicates a bridge operation …

feat(runtime-eden): add bridge_all_vesting_schedules
